import { runCommand } from "../command.ts";
import * as nix from "../nix.ts";
import type { SourceDefinition, SourceFiles } from "../source.ts";

export interface PackageOptions {
  /** npm distribution tag to track. */
  distTag?: string;
  /** Published npm package name. */
  name: string;
  /** npm registry base URL without a trailing slash. */
  registry?: string;
}

const defaultRegistry = "https://registry.npmjs.org";

function packageJson(name: string, version: string): string {
  const manifest = {
    name: "nix-repin-package",
    private: true,
    version,
    dependencies: { [name]: version },
  };
  return `${JSON.stringify(manifest, null, 2)}\n`;
}

function sourceNix(version: string, npmDepsHash: string): string {
  return `# This file is generated by nix-repin. Do not edit.

{ }:

{
  version = ${nix.string(version)};
  npmDepsHash = ${nix.string(npmDepsHash)};
}
`;
}

async function latestVersion(
  name: string,
  distTag: string,
  registry: string,
): Promise<string> {
  const url = `${registry}/${encodeURIComponent(name)}/${
    encodeURIComponent(distTag)
  }`;
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`${name}: ${url} returned ${response.status}`);
  }

  return (await response.json() as { version: string }).version;
}

async function lockedPackage(
  name: string,
  version: string,
  registry: string,
): Promise<SourceFiles> {
  const directory = await Deno.makeTempDir({ prefix: "nix-repin-npm-" });
  const manifest = packageJson(name, version);
  const lockPath = `${directory}/package-lock.json`;
  try {
    await Deno.writeTextFile(`${directory}/package.json`, manifest);
    await runCommand("npm", [
      "install",
      "--package-lock-only",
      "--ignore-scripts",
      "--no-audit",
      "--no-fund",
      `--registry=${registry}`,
    ], {
      cwd: directory,
      env: { NPM_CONFIG_CACHE: `${directory}/cache` },
    });

    const lock = await Deno.readTextFile(lockPath);
    const hash = await runCommand("prefetch-npm-deps", [lockPath]);
    return {
      "package.json": manifest,
      "package-lock.json": lock,
      "source.nix": sourceNix(version, hash),
    };
  } finally {
    await Deno.remove(directory, { recursive: true });
  }
}

/** Track an npm dist-tag and generate a lock file plus its fixed-output hash. */
export function pkg(options: PackageOptions): SourceDefinition {
  const registry = options.registry ?? defaultRegistry;

  return async () => {
    const version = await latestVersion(
      options.name,
      options.distTag ?? "latest",
      registry,
    );
    return lockedPackage(options.name, version, registry);
  };
}
