import { parse } from "@std/toml";

import * as nix from "./nix.ts";
import type { SourceFiles } from "./source.ts";

interface CargoPackage {
  name: string;
  source?: string;
  version: string;
}

interface CargoLock {
  package: CargoPackage[];
}

interface GitDependency {
  name: string;
  revision: string;
  url: string;
}

const header = "# This file is generated by nix-repin. Do not edit.\n\n";

function gitDependencies(contents: string): GitDependency[] {
  const dependencies = new Map<string, GitDependency>();
  const lock = parse(contents) as unknown as CargoLock;
  for (const package_ of lock.package) {
    if (!package_.source?.startsWith("git+")) {
      continue;
    }

    const url = new URL(package_.source.slice("git+".length));
    const revision = url.hash.slice(1);
    url.search = "";
    url.hash = "";
    if (!dependencies.has(revision)) {
      dependencies.set(revision, {
        name: `${package_.name}-${package_.version}`,
        revision,
        url: url.href,
      });
    }
  }

  return [...dependencies.values()];
}

function renderCargoLock(
  path: string,
  outputHashes: [name: string, hash: string][],
): string {
  const hashes = outputHashes
    .map(([name, hash]) => `    ${nix.string(name)} = ${nix.string(hash)};`)
    .join("\n");
  const outputHashesBinding = hashes
    ? `
  outputHashes = {
${hashes}
  };`
    : "";

  return `${header}{
  lockFile = ./${path};${outputHashesBinding}
}
`;
}

export async function lockFile(
  path: string,
  url: URL,
): Promise<SourceFiles> {
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`failed to download ${url}: ${response.status}`);
  }
  const contents = await response.text();
  const outputHashes = await Promise.all(
    gitDependencies(contents).map(async (dependency) =>
      [
        dependency.name,
        await nix.prefetchGit(dependency.url, dependency.revision),
      ] as [string, string]
    ),
  );

  return {
    [path]: contents,
    "cargo-lock.nix": renderCargoLock(path, outputHashes),
  };
}
