const decoder = new TextDecoder();
const header = "# This file is generated by nix-repin. Do not edit.\n\n";

export function string(value: string): string {
  return JSON.stringify(value).replaceAll("${", "\\${");
}

export async function prefetch(
  url: string,
  { unpack = false, name }: { unpack?: boolean; name?: string } = {},
): Promise<string> {
  const output = await new Deno.Command("nix", {
    args: [
      "store",
      "prefetch-file",
      "--json",
      ...(unpack ? ["--unpack"] : []),
      ...(name ? ["--name", name] : []),
      url,
    ],
  }).output();
  if (!output.success) {
    throw new Error(
      `nix store prefetch-file failed: ${decoder.decode(output.stderr).trim()}`,
    );
  }

  return JSON.parse(decoder.decode(output.stdout)).hash as string;
}

export async function prefetchGit(
  url: string,
  revision: string,
): Promise<string> {
  const output = await new Deno.Command("nix-prefetch-git", {
    args: [
      "--quiet",
      "--url",
      url,
      "--rev",
      revision,
    ],
  }).output();
  if (!output.success) {
    throw new Error(
      `nix-prefetch-git failed: ${decoder.decode(output.stderr).trim()}`,
    );
  }

  return JSON.parse(decoder.decode(output.stdout)).hash as string;
}

export function renderSource(
  inputs: string[],
  attributes: Record<string, string>,
  body: string,
): string {
  const parameters = `{ ${inputs.join(", ")} }:`;
  const bindings = Object.entries(attributes)
    .map(([name, value]) => `  ${name} = ${string(value)};`)
    .join("\n");
  const exported = [...Object.keys(attributes), "src"].join(" ");

  return `${header}${parameters}

let
${bindings}
${body}
in
{
  inherit ${exported};
}
`;
}
