import * as path from "@std/path";

const decoder = new TextDecoder();
const header = "# This file is generated by nix-repin. Do not edit.\n\n";

export interface PrefetchResult {
  hash: string;
  storePath: string;
}

export function string(value: string): string {
  return JSON.stringify(value).replaceAll("${", "\\${");
}

export async function prefetch(
  url: string,
  { unpack = false, name }: { unpack?: boolean; name?: string } = {},
): Promise<PrefetchResult> {
  const output = await new Deno.Command("nix", {
    args: [
      "store",
      "prefetch-file",
      "--json",
      ...(unpack ? ["--unpack"] : []),
      ...(name ? ["--name", name] : []),
      url,
    ],
  }).output();
  if (!output.success) {
    throw new Error(
      `nix store prefetch-file failed: ${decoder.decode(output.stderr).trim()}`,
    );
  }

  const { hash, storePath } = JSON.parse(
    decoder.decode(output.stdout),
  ) as PrefetchResult;

  return { hash, storePath };
}

export async function prefetchGit(
  url: string,
  revision: string,
): Promise<string> {
  const output = await new Deno.Command("nix-prefetch-git", {
    args: [
      "--quiet",
      "--url",
      url,
      "--rev",
      revision,
    ],
  }).output();
  if (!output.success) {
    throw new Error(
      `nix-prefetch-git failed: ${decoder.decode(output.stderr).trim()}`,
    );
  }

  return JSON.parse(decoder.decode(output.stdout)).hash as string;
}

/** Walk up from `from` to the repository flake that contains the package. */
export async function findFlakeRoot(from: string): Promise<string> {
  let directory = path.resolve(from);
  while (true) {
    try {
      if ((await Deno.stat(path.join(directory, "flake.nix"))).isFile) {
        return directory;
      }
    } catch (error) {
      if (!(error instanceof Deno.errors.NotFound)) {
        throw error;
      }
    }

    const parent = path.dirname(directory);
    if (parent === directory) {
      throw new Error(`no flake.nix found at or above ${from}`);
    }
    directory = parent;
  }
}

/**
 * Build an attribute of the repository flake's `nixpkgs` input for the current
 * system and return the store path of its `out` output.
 */
export async function buildNixpkgsPackage(
  packageDirectory: string,
  attribute: string,
): Promise<string> {
  const root = await findFlakeRoot(packageDirectory);
  const expression = `let
  flake = builtins.getFlake ${string(`path:${root}`)};
  pkgs = flake.inputs.nixpkgs.legacyPackages.\${builtins.currentSystem};
in
pkgs.${attribute}`;

  const output = await new Deno.Command("nix", {
    args: [
      "build",
      "--expr",
      expression,
      "--impure",
      "--json",
      "--no-link",
    ],
  }).output();
  if (!output.success) {
    throw new Error(
      `nix build ${attribute} failed: ${decoder.decode(output.stderr).trim()}`,
    );
  }

  const [result] = JSON.parse(decoder.decode(output.stdout)) as {
    outputs: Record<string, string>;
  }[];

  return result.outputs.out;
}

export function renderSource(
  inputs: string[],
  attributes: Record<string, string>,
  body: string,
): string {
  const parameters = `{ ${inputs.join(", ")} }:`;
  const bindings = Object.entries(attributes)
    .map(([name, value]) => `  ${name} = ${string(value)};`)
    .join("\n");
  const exported = [...Object.keys(attributes), "src"].join(" ");

  return `${header}${parameters}

let
${bindings}
${body}
in
{
  inherit ${exported};
}
`;
}
